baseurl: /book
title: 寻找理想的教育
subtitle: 我的全人教育之旅
author: 陈一帅
simple_search: http://bing.com/search
description:
name: book
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: main
transfer:
  command: rsync
  settings: -av
  source: _site/
